WIP: Fix stuff after running kola external tests

diff --git a/builder/Containerfile b/builder/Containerfile
--- a/builder/Containerfile
+++ b/builder/Containerfile
@@ -1,21 +1,29 @@
 FROM quay.io/fedora/fedora-bootc:43
-RUN dnf install -y ignition ignition-grub bsdtar
+# NetworkManager-team and teamd are needed for cosa external test in fcc
+RUN dnf install -y ignition ignition-grub \ 
+    bsdtar afterburn afterburn-dracut NetworkManager-team teamd \
+    nmstate iscsi-initiator-utils sg3_utils \
+    clevis clevis-luks clevis-dracut clevis-systemd \
+    cryptsetup
 
 # Add ssh support
 COPY ../conf/sshd/40-authorized-keys-file.conf /etc/ssh/sshd_config.d/40-authorized-keys-file.conf
 
 # Copy dracut conf
-COPY ../dracut/dracut.conf.d/* /usr/lib/dracut/dracut.conf.d/
+COPY ../dracut/dracut.conf.d/ /usr/lib/dracut/dracut.conf.d/
 
 # Copy dracut modules
 RUN mkdir -p /usr/lib/dracut/modules.d/40ignition-ostree
-COPY ../dracut/40ignition-ostree/* /usr/lib/dracut/modules.d/40ignition-ostree
+COPY ../dracut/40ignition-ostree/ /usr/lib/dracut/modules.d/40ignition-ostree
 ## Copy rdcore
 RUN mkdir -p /usr/lib/dracut/modules.d/50rdcore
 COPY ../dracut/50rdcore/* /usr/lib/dracut/modules.d/50rdcore
 ## Copy coreos-ignition and coreos-live dracut module
 RUN mkdir -p /usr/lib/dracut/modules.d/35coreos-ignition
-COPY ../dracut/35coreos-ignition/* /usr/lib/dracut/modules.d/35coreos-ignition
+COPY ../dracut/35coreos-ignition/ /usr/lib/dracut/modules.d/35coreos-ignition
+## Copy ignition-conf dracut module
+RUN mkdir -p /usr/lib/dracut/modules.d/40ignition-conf
+COPY ../dracut/40ignition-conf/ /usr/lib/dracut/modules.d/40ignition-conf
 
 ## Copy dracut module to remove systemd-gpt-auto-generator from initramfs
 ## Ref: https://github.com/coreos/fedora-coreos-config/commit/2baab77b4d3099b67a97a48ec99b136861866113#diff-768a2aa1ee18b2997a1c8f0edf733da0b1b15fcaf00a1d0a4df2c71d41cc9675
@@ -24,11 +32,15 @@ COPY ../dracut/50remove-systemd-gpt-auto-generator/* /usr/lib/dracut/modules.d/5
 
 # Copy 99emergency-shell-setup module
 RUN mkdir -p /usr/lib/dracut/modules.d/99emergency-shell-setup
-COPY ../dracut/99emergency-shell-setup/* /usr/lib/dracut/modules.d/99emergency-shell-setup
+COPY ../dracut/99emergency-shell-setup/ /usr/lib/dracut/modules.d/99emergency-shell-setup
 
 # Copy 99journal-conf module
 RUN mkdir -p /usr/lib/dracut/modules.d/99journal-conf
-COPY ../dracut/99journal-conf/* /usr/lib/dracut/modules.d/99journal-conf
+COPY ../dracut/99journal-conf/ /usr/lib/dracut/modules.d/99journal-conf
+
+# Copy multipath dracut modules
+RUN mkdir -p /usr/lib/dracut/modules.d/35coreos-multipath
+COPY ../dracut/35coreos-multipath/ /usr/lib/dracut/modules.d/35coreos-multipath
 
 # This needs to go from the image as well.
 # Ref: https://github.com/coreos/fedora-coreos-config/commit/2baab77b4d3099b67a97a48ec99b136861866113#diff-768a2aa1ee18b2997a1c8f0edf733da0b1b15fcaf00a1d0a4df2c71d41cc9675
@@ -39,14 +51,13 @@ COPY ../scripts/opt-usr-local-symlink.sh /usr/libexec/
 RUN chmod +x /usr/libexec/opt-usr-local-symlink.sh && /usr/libexec/opt-usr-local-symlink.sh
 RUN rm /usr/libexec/opt-usr-local-symlink.sh
 
-
 # Copy systemd stuff
 ## Copy system-generators
-COPY ../systemd/system-generators/* /usr/lib/systemd/system-generators/
+COPY ../systemd/system-generators/ /usr/lib/systemd/system-generators/
 ## Copy systemd presets
-COPY ../systemd/system-preset/* /usr/lib/systemd/system-preset/
+COPY ../systemd/system-preset/ /usr/lib/systemd/system-preset/
 ## Copy systemd units
-COPY ../systemd/system/* /usr/lib/systemd/system/
+COPY ../systemd/system/ /usr/lib/systemd/system/
 
 # Systemd presets are not evaluated if this exists.
 # Switching to cosa osbuild should get rid of this?
@@ -58,7 +69,7 @@ COPY ../image.json /usr/share/coreos-assembler/image.json
 
 # Copy generator-lib.sh. This is need by coreos-live.
 RUN mkdir -p /usr/lib/coreos
-COPY ../coreos/* /usr/lib/coreos/
+COPY ../coreos/ /usr/lib/coreos/
 
 # Copy libexec scripts
 COPY ../scripts/libexec/* /usr/libexec/
@@ -66,20 +77,57 @@ COPY ../scripts/libexec/* /usr/libexec/
 # Enable ignition dracut module
 RUN echo 'add_dracutmodules+=" ignition "' > /usr/lib/dracut/dracut.conf.d/50-ignition.conf
 
-# regenerate the initramfs
-RUN set -xe; kver=$(ls /usr/lib/modules); env DRACUT_NO_XATTR=1 dracut -vf /usr/lib/modules/$kver/initramfs.img "$kver"
+# Copy coreos-network dracut module
+RUN mkdir -p /usr/lib/dracut/modules.d/35coreos-network
+COPY ../dracut/35coreos-network/ /usr/lib/dracut/modules.d/35coreos-network
+
+# Copy scsi-rules dracut module
+RUN mkdir -p /usr/lib/dracut/modules.d/01scsi-rules
+COPY ../dracut/01scsi-rules/ /usr/lib/dracut/modules.d/01scsi-rules
 
 RUN mkdir -p /usr/share/coreos-assembler
 COPY ../image.json /usr/share/coreos-assembler/image.json
+COPY ../platforms.json /usr/share/coreos-assembler/platforms.json
 
 # add os-release variant id
 RUN echo VARIANT_ID=coreos >> /usr/lib/os-release
 
 # add sudoers.d/passwordless-sudo
 COPY ../conf/sudoers.d/passwordless-sudo /etc/sudoers.d/passwordless-sudo
-RUN chmod 600 /etc/sudoers.d/passwordless-sudo
+RUN chmod 440 /etc/sudoers.d/passwordless-sudo
 
-RUN useradd -m -G wheel -s /bin/bash -p "" core
+COPY ../conf/sudoers.d/coreos-sudo-group /etc/sudoers.d/coreos-sudo-group
+RUN chmod 440 /etc/sudoers.d/coreos-sudo-group
 
 COPY ../conf/kargs.d/00-console.toml /usr/lib/bootc/kargs.d/00-console.toml
+
+# Copy udev rules
+COPY ../conf/udev/rules.d/ /usr/lib/udev/rules.d/
+
+RUN rm -v /usr/lib/systemd/system/local-fs.target.wants/bootc-generic-growpart.service
+
+RUN systemctl mask dnsmasq.service
+
+# Copy populate-lvm-devices systemd unit, preset and script
+#COPY ../systemd/system/coreos-populate-lvmdevices.service /usr/lib/systemd/system/coreos-populate-lvmdevices.service
+#COPY ../systemd/system-preset/45-coreos-populate-lvmdevices.preset /usr/lib/systemd/system-preset/45-coreos-populate-lvmdevices.preset
+COPY ../scripts/libexec/coreos-populate-lvmdevices /usr/libexec/coreos-populate-lvmdevices
+
+COPY ../conf/lvm/devices/system.devices /etc/lvm/devices/system.devices
+
+# dnsmasq is needed? `ext.config.ignition.systemd-unmasking` fails without it
+# device-mapper-multipath is needed for multipath support.
+RUN dnf install -y device-mapper-multipath
+
+RUN systemctl mask systemd-repart.service
+
+# Do we need this?
+COPY ../conf/tmpfiles.d/root-bash.conf /etc/tmpfiles.d/root-bash.conf
+
+# regenerate the initramfs
+RUN set -xe; kver=$(ls /usr/lib/modules); env DRACUT_NO_XATTR=1 dracut -vf /usr/lib/modules/$kver/initramfs.img "$kver"
+
+# Needed for, only, some tests to pass.
+RUN groupadd -g 16 sudo
+
 LABEL com.coreos.osname=fedora-coreos
